services:
    helit.myclass.twig.myclass_extension:
        class: Helit\Bundle\MyClassBundle\Twig\HelitMyClassExtension
        tags:
            - { name: twig.extension }
    helit.myclass.student_info.manager:
        class: Helit\Bundle\MyClassBundle\StudentInfo\StudentInfoManager
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
