helit_my_class:
    resource: "@HelitMyClassBundle/Controller/"
    type:     annotation
    prefix:   /

index_php:
    path: /index.php
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: helit_my_class_landing_index
        permanent: true
