fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

my_class:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

index_php:
    path: /index.php
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: my_class_landing_index
        permanent: true
