<?php

namespace Helit\Bundle\MyClassBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ScheduleItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleItemRepository extends EntityRepository
{
}
